# Generated by Django 4.1 on 2024-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collisionconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pronoun',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pronoun'),
        ),
        migrations.AlterField(
            model_name='person',
            name='topics',
            field=models.JSONField(blank=True, verbose_name='Topics'),
        ),
    ]
