# Generated by Django 4.1 on 2024-06-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collisionconf', '0002_alter_person_pronoun_alter_person_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='industry',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='topics',
            field=models.JSONField(blank=True, null=True, verbose_name='Topics'),
        ),
    ]
